### ISSUE TITLE
NERDTree-o does not behave as expected

### ISSUE THREAD

**Issue by agibralter** [Xuyuanp/git-nerdtree#10]
https://github.com/Xuyuanp/git-nerdtree/blob/master/doc/NERD_tree.txt#L267-L284

This is an issue in https://github.com/scrooloose/nerdtree (https://github.com/scrooloose/nerdtree/issues/170), but that repo doesn't seem to be getting much love these days...

Basically, if you have two tabs open tabA and tabB with NERDTree open in each, when you open a file in tabA's NERDTree and then try to open the same file in tabB's NERDTree, it jumps to tabB rather than opening the file "in the last window" (in tabB). NERDTree-go, on the other hand, works as expected.

**Comment by Xuyuanp** [comment]
Thank you for your trust! I will try to fix it. But I can't promise anything, as this plugin is so complicated.

**Comment by agibralter** [comment]
Heh, sorry, I didn't mean to put any pressure! I started digging around the repo but I'm not sure where anything is! :)

**Comment by agibralter** [comment]
Maybe something in this part of the diff: https://github.com/scrooloose/nerdtree/compare/4.2.0...2cb0fc78fb#diff-5f5ebf659174a2d71cf1e3ebbd924fb8L1116

**Comment by Xuyuanp** [comment]
scrooloose is back. He will fix this.
