### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ladislas** [Xuyuanp/git-nerdtree#12]
Just to say that I love what you've done with NerdTree, it's great! :)

Keep on the good work!

**Comment by Xuyuanp** [comment]
I'm sosososososos sorry! I forgot to remove the debug message.
I have fixed it already.

**Comment by altV** [comment]
hello!
can I ask you what's the plugin on the top of your recorded demo, where you select git commands from the list?

**Comment by Xuyuanp** [comment]
@altV unite.vim by @Shougo
It's a very powerfull plugin! You can do almost anything with it.

See also in my [vimrc](https://github.com/Xuyuanp/vimrc.git)
