### ISSUE TITLE
Is there a way to integrate without forking?

### ISSUE THREAD

**Issue by NewAlexandria** [Xuyuanp/git-nerdtree#4]
I see pros and cons.
- A fork is more durable because it is locked in time to the NERDTree code with which the mod works.
- a fork can fall out of date if the project is not maintained, or if updating to new releases of the parent

is there way to 'plugin to NERDTree?  
- I realize that, even if so, this is potentially more brittle, and can if unmaintained can leave code that is attached to an old version of NERDTree that may be less-than-convenient to get

**Comment by Xuyuanp** [comment]
I have tried to implement this function as a plugin of nerdtree too. But nerdtree doesn't provide interface to change the displayed string before rendering.
I am refactoring code, and I will ask to the author for some hook when my code is clean enough. But I haven't got a perfect way till now.

You can use my fork without worrying now. Nerd tree last update was 11 months ago. But I'm watching it, I will merge it immediately after a new version released.

**Comment by NewAlexandria** [comment]
I saw a similar pattern to this with [the solarized repo](https://github.com/altercation/solarized).  Sometimes it happens; things change; cycle of life, yada yada.  

If your repo is the one that will be more-regularly maintained, and you don't introduce inefficiencies / etc, then I have no problem to be one of the voices in support of it being the primarily-maintained repo.  I will use it [in my IDE setup](https://github.com/NewAlexandria/vim.ana/blob/master/.gitmodules#L37).  Best.

**Comment by Xuyuanp** [comment]
I have to say sorry first. As you know, I am Chinese and not good at English, so I don't really know what are you saying. 
I guess that you wish I could make the readme more completely and write change log after each updating, etc. Right?

**Comment by NewAlexandria** [comment]
Oh, no!  My primary meaning was that I like what you have done and plan to use this repo at the primary unless either a). @scrooloose merge's or collaborates on a plugin format, or b). something else turns up as a problem.   Thank you for your commitment to keep it updated; I'm sure you will since you will want that for your own purposes, too.

I think your README is ok.

**Comment by Xuyuanp** [comment]
I'm so glad that this is helpful for you.
