### ISSUE TITLE
It doesn't work in my Linux Mint16 vim7.4 !

### ISSUE THREAD

**Issue by yxjxx** [Xuyuanp/git-nerdtree#6]
Should I do something more?
![my .vimrc](http://ww2.sinaimg.cn/large/81d2b157gw1efquv8or9bj20n007ytat.jpg)

**Comment by Xuyuanp** [comment]
What's the "doesn't work" meaning?  Could you show me a screenshot?

**Comment by yxjxx** [comment]
There is already a screenshot actually。Try refresh the page?"doesn't work" means I didn't see any change after install the plugin,there is no git status showing besides the filename like your example gif showing.

**Comment by bmedicke** [comment]
It looks like you added the original and the fork:

```
Bundle 'scrooloose/nerdtree'
Bundle 'jistr/vim-nerdtree-tabs'
Bundle 'Xuyuanp/git-nerdtree'
```

It's a self-contained replacement for nerdtree, so if you ditch the first line it should work.

**Comment by yxjxx** [comment]
@bmedicke Yeap,that's it! It works fine now.Very thanks! :)
