### ISSUE TITLE
error when start vim up.

### ISSUE THREAD

**Issue by xiujunma** [Xuyuanp/git-nerdtree#9]
E128: Function name must start with a capital or "s:": plugin:NERDTreeGitStatusRefresh()

I upgrade vim to 7.4.273 using homebrew, it is ok in previous version, and 'scrooloose/nerdtree' is ok.

**Comment by tpoisot** [comment]
Same problem here.

**Comment by Xuyuanp** [comment]
I'm not sure what's wrong. It works here with 7.4.52 using homebrew.

I create a new branch [hotfix/5.0.1](https://github.com/Xuyuanp/git-nerdtree/tree/hotfix/5.0.1). Could you have a try and tell me the result?

**Comment by xiujunma** [comment]
I have tried hotfix/5.0.1 branch, works well with 7.4.273, thanks very much.

**Comment by Xuyuanp** [comment]
Well!

You can switch master now.
